### ISSUE TITLE
osmocombb.yml - references are wrong

### ISSUE THREAD

**Issue by bibi1959** [bbaranoff/osmocombb-ansible#2]
name: osmocombb-trx
    shell: cd /root && rm -rf /root/osmocom-ansible && git clone https://github.com/bbaranoff/osmocom-ansible && rm -rf /root/trx /root/osmocom-bb && cd /root && export PATH=$PATH:/root/gnuarm/install/bin && git clone https://github.com/osmocom/osmocom-bb trx && cd /root/trx/src && git checkout jolly/testing && cp /root/osmocom-ansible/tx_enable.patch /root/trx/src/tx_enable.patch && patch -p1 < tx_enable.patch && make HOST_layer23_CONFARGS=--enable-transceiver

This does not work. the only repo available here is osmocombb-ansible

**Comment by bbaranoff** [comment]
changed to osmocombb-ansible to all occurences sorry
