### ISSUE TITLE
Ansible connection error - 

### ISSUE THREAD

**Issue by bibi1959** [bbaranoff/osmocombb-ansible#3]
#ansible all -m ping
localhost | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: ", 
    "unreachable": true
}

key installed correctly - 

ssh to localhost works.
permitted by applicable law.
Last login: Tue Apr 17 15:57:30 2018 from ::1

**Comment by bbaranoff** [comment]
I don't know what you have made wrong. It works on a fresh install with me. Are you root? Try again from the beginning with the root account.

**Comment by bibi1959** [comment]
Solved. 

Ansible by default tries to connect through ssh. For localhost you should set the connection to **local**.
ansible-playbook osmocombb.yml **--connection=local**

**ansible all -m ping --connection=local**
localhost | SUCCESS => {
    "changed": false, 
    "ping": "pong"

and i am afraiud
